export const image: any = {
  legacyOrbLogo: require("./legacyOrb.png"),
  leftArrow: require("./leftArrow.png"),
  rightArrow: require("./rightArrow.png"),
  chat: require("./chat.png"),
  paperPin: require("./paperPin.png"),
  calender: require("./calender.png"),
  microphone: require("./microphone.png"),
  hamburger: require("./hamburger.png"),
  notification: require("./notification.png"),
  help: require("./help.png"),
  lock: require("./lock.png"),
  user: require("./user.png"),
  signOut: require("./signOut.png"),
  edit: require("./edit.png"),
  send: require("./send.png"),
  eye: require("./eye.png"),
  eyeOff: require("./eye-off.png"),
  play: require("./play.png"),
  close: require("./close.png"),
  pause: require("./pause.png"),
  delete: require("./delete.png"),
  dummyUser: require("./dummyUserIcon.png"),
  incorrect: require("./incorrect.png"),
  check: require("./check.png"),
  plus: require("./plus.png"),
  resetPassword: require("./reset-password.png"),
};
